# NUMPY

In [1]:
import numpy as np

# Aggregate Functions

In [2]:
# Array-wise sum

a=np.array([1,2,5,8,9])
print(a)
c=a.sum()
print("sum of Array :", c)

[1 2 5 8 9]
sum of Array : 25


In [3]:
# Array-wise minimum value

a=np.array([8,9,7,3,6])
print(a)
b=a.min()
print("Minimun value :", b)

[8 9 7 3 6]
Minimun value : 3


In [4]:
# Maximum value of an array row

a=np.array([8,6,4,0,9])
print(a)
b=a.max(axis=0)
print("Maximum value :", b)

[8 6 4 0 9]
Maximum value : 9


In [5]:
# Row Cumulative sum of the elements

a=np.array([[1,2,5,6,3],[7,8,9,2,3]])
print(a)
b=a.cumsum(axis=0)
print("Cumulative sum :", b)

[[1 2 5 6 3]
 [7 8 9 2 3]]
Cumulative sum : [[ 1  2  5  6  3]
 [ 8 10 14  8  6]]


In [6]:
# Cumulative sum of the elements

a=np.array([[1,2,5,6,3],[7,8,9,2,3]])
print(a)
b=a.cumsum(axis=1)
print("Cumulative sum :", b)

[[1 2 5 6 3]
 [7 8 9 2 3]]
Cumulative sum : [[ 1  3  8 14 17]
 [ 7 15 24 26 29]]


In [7]:
# Mean value

a=np.array([4,8,6,0,3])
print(a)
b=a.mean()
print("Mean value :", b)

[4 8 6 0 3]
Mean value : 4.2


In [8]:
# Median value

a=np.array([1,2,3,4,5])
print(a)
b=np.median(a)
print("Median value :", b)

[1 2 3 4 5]
Median value : 3.0


In [9]:
#  Correlation coefficient

a=np.array([8,6,4,0,9])
print(a)
b=np.corrcoef(a)
print("Coorelation :", b)

[8 6 4 0 9]
Coorelation : 1.0


In [10]:
#  Correlation coefficient


a=np.array([[1,2,3],[4,8,5]])
print(a)
b=np.corrcoef(a)
print("Coorelation :", b)

[[1 2 3]
 [4 8 5]]
Coorelation : [[1.         0.24019223]
 [0.24019223 1.        ]]


In [11]:
# Standard deviation

a=np.array([7,8,9,2,4])
print(a)
b=np.std(a)
print("Standard Deviation :", b)

[7 8 9 2 4]
Standard Deviation : 2.6076809620810595


In [12]:
#  Standard Deviation

a=np.array([[1,2,3],[4,8,5]])
print(a)
b=np.std(a)
print("Standard Deviation :", b)

[[1 2 3]
 [4 8 5]]
Standard Deviation : 2.266911751455907


#  Comparison

In [14]:
# Element-wise comparison

a=np.array([1,7,5,6])
b=np.array([3,4,2,9])
c=a==b
print("Element-wise comparison :", c)

Element-wise comparison : [False False False False]


In [15]:
# Element-wise comparison

a=np.array([1,7,5,6])
b=np.array([1,4,5,9])
c=a==b
print("Element-wise comparison :", c)

Element-wise comparison : [ True False  True False]


In [16]:
# Array-wise comparison

a=np.array([1,7,5,6])
b=np.array([1,4,5,9])
c=np.array_equal(a,b)
print("Array-wise comparison  :", c)

Array-wise comparison  : False


In [17]:
 # Array-wise comparison

a=np.array([1,4,5,9])
b=np.array([1,4,5,9])
c=np.array_equal(a,b)
print("Array-wise comparison  :", c)

Array-wise comparison  : True


In [19]:
# Element-wise comparison

a=np.array([1,7,5,6])
b=a<2
print("Element-wise comparison :", b)

[ True False False False]


In [22]:
# Element-wise comparison

a=np.array([1,3,5,2])
b=a<5
print("Element-wise comparison :", b)

Element-wise comparison : [ True  True False  True]


In [23]:
# Element-wise comparison

a=np.array([1,3,5,2])
b=a<=5
print("Element-wise comparison :", b)

Element-wise comparison : [ True  True  True  True]


In [ ]:
Indexing
Boolean Indexing
a[a<2] #Select elements from a less than 2
array([1])
Fancy Indexing
b[[1, 0, 1, 0],[0, 1, 2, 0]] #Select elements (1,0),(0,1),(1,2) and (0,0)
array([ 4. , 2. , 6. , 1.5])
b[[1, 0, 1, 0]][:,[0,1,2,0]] #Select a subset of the matrix’s rows and columns
array([[ 4. ,5. , 6. , 4. ],
[ 1.5, 2. , 3. , 1.5],
[ 4. , 5. , 6. , 4. ],
[ 1.5, 2. , 3. , 1.5]]

# Indexing 

# Boolean Indexing

In [31]:
# Select elements from a less than 2

a=np.array([1,8,9,0])
b=a[a<2]
print("elements from a less than 2 :  ", b)

elements from a less than 2 :   [1 0]


# Fancy Indexing

In [41]:
# Selecting Element

a= np.array([1, 2, 3, 4, 5, 6, 7, 8])
b= a[[1,3,5,7]]
print("select_element : ",b)

select_element :  [2 4 6 8]


In [42]:
# Single & Multiple Element

a= np.array([1, 2, 3, 4, 5, 6, 7, 8])
simple_indexing = a[3]
print("Simple Indexing:",simple_indexing)   
fancy_indexing = a[[1, 2, 5, 7]]
print("Fancy Indexing:",fancy_indexing)   

Simple Indexing: 4
Fancy Indexing: [2 3 6 8]


In [49]:
a= np.array([[1, 3, 5], 
                [11, 7, 9], 
                [13, 18, 29]])

# create an array of row indices
row= np.array([0, 2])

# use fancy indexing to select specific rows
selected_row = a[row, :]

print("Selecting The Row :",selected_row)

Selecting The Row : [[ 1  3  5]
 [13 18 29]]


In [62]:
# Indexing and Sorting (Ascending & Descending)

a= np.array([3, 2, 6, 1, 8, 5, 7, 4])

# sort array1 using fancy indexing in descending order
des_sort= a[np.argsort(-a)]
print("Sorting The Array In Descending Order  :", des_sort)

Sorting The Array In Descending Order  : [8 7 6 5 4 3 2 1]


In [61]:
# Indexing and Sorting (Ascending & Descending)

a= np.array([3, 2, 6, 1, 8, 5, 7, 4])

# sort array1 using fancy indexing in ascending order
asc_sort=a[np.argsort(a)]
print("Sorting The Array In Ascending order  :", asc_sort)

Sorting The Array In Ascending order  : [1 2 3 4 5 6 7 8]
