# NUMPY

In [1]:
import numpy as np

# Subsetting , Slicing

# Subsetting

In [2]:
# Select the element at the 2nd index

a=np.array([1,8,9,3,5])
print(a)
c=a[2]
print("Selecting the element :", c)

[1 8 9 3 5]
Selecting the element : 9


In [3]:
# Select the element at row 0 column 2 (equivalent to b[0][2])

a=np.array([[1,8,9,8,5],[2,9,1,4,7]])
b=a[0,3]
print("Select the element at row 0 column 2  :", b)

Select the element at row 0 column 2  : 8


In [4]:
# Select the element at row 1 column 2 (equivalent to b[1][2])

a=np.array([[1,8,9,8,5],[2,9,1,4,7]])
b=a[1,4]
print("Select the element at row 1 column 2  :", b)

Select the element at row 1 column 2  : 7


# Slicing

In [5]:
#Reversed array a array

a=np.array([17,80,48,10,15])
b=a[: : -1]
print("Reverse array :" ,b)

Reverse array : [15 10 48 80 17]


In [6]:
# Select items at index 0 and 1

a=np.array([1,8,9,8,5])
b=a[0:2]
print("Select items at index :", b)
            

Select items at index : [1 8]


In [7]:
# Select items at rows 0 and 1 in column 1

a=np.array([[1,8,7,6,5],[2,3,0,14,7]])
b=a[0:2,1]
print("Select items at rows and column  :", b)

Select items at rows and column  : [8 3]


In [8]:
# Select all items at row 

a=np.array([[1,8,7,6,5],[2,3,0,14,7]])
b=a[:1]
print("Select items at rows and column  :", b)

Select items at rows and column  : [[1 8 7 6 5]]


In [9]:
# Select all items at row 0 (equivalent to b[0:1, :])

a=np.array([[[1,8,7,6,5],[2,3,0,14,7],[11,12,13,15,16]]])
b=a[0:1,:2]
print("Select items at rows and column  :", b)

Select items at rows and column  : [[[ 1  8  7  6  5]
  [ 2  3  0 14  7]]]


In [10]:
# Select all items at row and column Same as [1,:,:]

a=np.array([[[1,8,7,],[2,3,0],[7,0,9]]])
b=a[:,:2,:]
print("Select items at rows and column  :", b)

Select items at rows and column  : [[[1 8 7]
  [2 3 0]]]


# Array Manipulation

In [11]:
#  Transpose array

a=np.array([[1,8,5],[2,5,6]])
print(a)
b=np.transpose(a)
print("transpose array : ", b)

[[1 8 5]
 [2 5 6]]
transpose array :  [[1 2]
 [8 5]
 [5 6]]


In [12]:
a=np.array([[1,8,5],[2,5,6]])
a.T 

array([[1, 2],
       [8, 5],
       [5, 6]])

In [13]:
#  Changing Array Shape
#  Flatten the array

a=np.array([[1,8,5],[2,5,6]])
a.ravel()

array([1, 8, 5, 2, 5, 6])

In [14]:
# Reshape, but don’t change data 

a=np.array([[1,8,5],[2,5,1]])
a.reshape(3,-2)

array([[1, 8],
       [5, 2],
       [5, 1]])

# Adding/Removing Elements

In [15]:
# Return a new array with shape (1,5)

a=np.array([[1,8,5],[2,5,1]])
a.resize(1,5)
print("Shape of  an Array :", a)

Shape of  an Array : [[1 8 5 2 5]]


In [16]:
# Return a new array with shape (2,6)

a=np.array([[1,8,5],[2,5,1]])
a.resize(2,5)

In [17]:
#Append items to an array

a=np.array([1,8,5])
b=np.array([2,5,1])
print("append the item  :" ,np.append(a,b))

append the item  : [1 8 5 2 5 1]


In [18]:
# Insert items in an array

a=np.array([1,0,5,8,3])
print("Insert element  :", np.insert(a,1,7))

Insert element  : [1 7 0 5 8 3]


In [19]:
# Insert items in an array

a=np.array([1,0,5,8,3])
print("Insert element  :", np.insert(a,4,7))

Insert element  : [1 0 5 8 7 3]


In [20]:
# Delete items from an array

a=np.array([1,27,16,18,77])
print("Delete element  :", np.delete(a,[3]))

Delete element  : [ 1 27 16 77]


#  Combining Arrays

In [21]:
# Concatenate arrays

a=np.array([1,2,3])
b=np.array([4,5,6])
print("Concatenate arrays  :" , np.concatenate((a,b),axis=0))

Concatenate arrays  : [1 2 3 4 5 6]


In [22]:
# Stack arrays vertically (row-wise)

a=np.array([1,2,3])
b=np.array([4,5,6])
print("vertically row-wise  :" , np.vstack((a,b)))

vertically row-wise  : [[1 2 3]
 [4 5 6]]


In [23]:
np.r_[a,b]

array([1, 2, 3, 4, 5, 6])

In [24]:
# Stack arrays horizontally (column-wise)

a=np.array([11,29,3])
b=np.array([45,5,56])
print(" horizontally column-wise  :",np.hstack((a,b)))

 horizontally column-wise  : [11 29  3 45  5 56]


In [25]:
#Create stacked column-wise arrays

a=np.array([10,9,43])
b=np.array([65,50,6])
print(" Satck column-wise  :",np.column_stack((a,b)))

 Satck column-wise  : [[10 65]
 [ 9 50]
 [43  6]]


In [26]:
np.c_[a,b]

array([[10, 65],
       [ 9, 50],
       [43,  6]])

#  Splitting Arrays

In [28]:
#  Split the array horizontally at the 3rd index

a=np.array([10,9,43])
print("Split the array horizontally  :", np.hsplit(a,3))

Split the array horizontally  : [array([10]), array([9]), array([43])]


In [29]:
# Split the array vertically at the 1st index

a=np.array([[9,7,2,4],[8,0,7,3]])
print("Split the array vertically  : ", np.vsplit(a,1))

Split the array vertically  :  [array([[9, 7, 2, 4],
       [8, 0, 7, 3]])]


In [30]:
# Split the array vertically at the 2nd index

a=np.array([[9,7,2,4],[8,0,7,3]])
print("Split the array vertically  : ", np.vsplit(a,2))

Split the array vertically  :  [array([[9, 7, 2, 4]]), array([[8, 0, 7, 3]])]


#  Asking For Help

In [31]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
