# Numpy

In [1]:
import numpy as np

# Create Array

In [2]:
# create 1-D array

a=np.array([1,2,3])
print(a)
print("dimension",a.ndim)

[1 2 3]
dimension 1


In [3]:
# create 2-D array

a=np.array([[1,2,3],[4,5,6]])
print(a)
print("dimension",a.ndim)

[[1 2 3]
 [4 5 6]]
dimension 2


In [4]:
# create 3-D array

a=np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(a)
print("dimension",a.ndim)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
dimension 3


In [5]:
# create an arrays of ZEROS

a=np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [6]:
# create an arrays of ONES

a=np.ones((1,2))
print(a)
print("dimension",a.ndim)
print(type(a))

[[1. 1.]]
dimension 2
<class 'numpy.ndarray'>


In [7]:
# create an arrays of ONES

a=np.ones((2,3,4),dtype=np.int16)
print(a)
print("dimension",a.ndim)
print(type(1))

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
dimension 3
<class 'int'>


In [8]:
# create anarray of evenly spaced value (STEP VALUE)

a=np.arange(10,25,5)
print(a)
print("dimension",a.ndim)

[10 15 20]
dimension 1


In [9]:
# create an array of evenly spaced value 

a=np.linspace(0,1,9)
print(a)
print("dimension",a.ndim)

[0.    0.125 0.25  0.375 0.5   0.625 0.75  0.875 1.   ]
dimension 1


In [10]:
# create an constant array

a=np.full((2,4),7)
print(a)
print("dimension",a.ndim)

[[7 7 7 7]
 [7 7 7 7]]
dimension 2


In [11]:
# create a 2x2 identity matrix

a=np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [12]:
# create a 3x3 identity matrix

a=np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
# create an array with random values

a=np.random.random((3))
a

array([0.87382951, 0.37637391, 0.45426884])

In [14]:
# create an empty array

a=np.empty((3,2))
a

array([[1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309],
       [1.39069238e-309, 1.39069238e-309]])

# Inspecting Your Array

In [15]:
a=np.array([1,2,3,4,5,6])
print(a)

print("Shape of array",a.shape)                                       #Array dimensions
print("Length of array ",len(a))                                      #Length of Array
print("Number of array dimensions",a.ndim)                            #Number of array dimensions
print("Number of array elements",a.size)                              #Number of array elements
print("Data type of array elements",a.dtype)                          #Data type of array elements
print("Name of data type",a.dtype.name)                               #Name of data type
print("Convert an array to a different type",a.astype(float))         #Convert an array to a different type

[1 2 3 4 5 6]
Shape of array (6,)
Length of array  6
Number of array dimensions 1
Number of array elements 6
Data type of array elements int32
Name of data type int32
Convert an array to a different type [1. 2. 3. 4. 5. 6.]


# Data Types

In [16]:
np.int64                     #Signed 64-bit integer types
# np.float32                 #Standard double-precision floating point
# np.complex                 #Complex numbers represented by 128 floats
# np.bool                    #Boolean type storing TRUE and FALSE values Numpy
# np.object                  #Python object type
# np.string_                 #Fixed-length string type
# np.unicode_                #Fixed-length unicode type

numpy.int64

# Copying Arrays

In [17]:
# view of array

a=np.array([1,2,3,4])
print(a)
h=a.view()
print("hview",h)


[1 2 3 4]
hview [1 2 3 4]


In [18]:
# copy of array

a=np.array([1,2,3,4])
print(a)
h=a.view()
print("hview",h)
np.copy(a)
h=a.copy()
print("hcopy",h)

[1 2 3 4]
hview [1 2 3 4]
hcopy [1 2 3 4]


# Solving & Loading On Disk

In [19]:
# Save Array

a=np.array([1,2,3,4])
np.save("my_array",a)
a

array([1, 2, 3, 4])

In [21]:
np.savez('array.npz')

In [22]:
# loading the array

np.load('my_array.npy')

array([1, 2, 3, 4])

# Sorting Array

In [ ]:
a=np.array([12,45,36,78,95,16,0,100,2])
print(a)

In [ ]:
#  Sort Array

a.sort()
print("Sort Of An Array",a)

In [ ]:
b=np.array([75,84,1,95,36,42])
print(b)

In [ ]:
#  Sort the elements of an array's axis

b.sort(axis=0) 
print("Sort Of An Array",b)

#  Array Mathematics  , Arithmetic Operations

In [ ]:
# Addition of two Arrays 

a=np.array([1,2,3])
b=np.array([4,5,6])
c=np.add(b,a)
print("Sum Of Two Array",c)

In [ ]:
# Subtraction of two Arrays 

a=np.array([4,5,6])
b=np.array([1,2,3])
c=np.subtract(a,b)
print("Subtract Of Two Array",c)

In [ ]:
# Multiplly of two Arrays 

a=np.array([6,3,5])
b=np.array([1,2,3])
c=np.multiply(a,b)
print("Multiply Of Two Array",c)

In [ ]:
# Dividing of two Arrays 

a=np.array([4,5,6])
b=np.array([1,2,3])
c=np.divide(a,b)
print("Divide Of Two Array",c)

In [ ]:
#Exponentiation

a=np.array([2,3,6])
c=np.exp(a) 
print("Exponentiation",c)

In [ ]:
#Square root

a=np.array([25,64,81,36])
b=np.sqrt(a)
print("Square root Of An Array",b)

In [ ]:
#Print sines of an array

a=np.array([90,0,60,30])
np.sin(a)

In [ ]:
#Element-wise cosi

a=np.array([0,30,45,90])
np.cos(a)

In [ ]:
# log

a=np.array([5,2,3])
np.log(a) 

In [ ]:
# Dot Product

a=np.array([1,2,3])
b=np.array([4,5,6])
a.dot(b)